package com.esprit.controllers;

import com.esprit.models.Evenement;
import com.esprit.services.EvenementService;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.scene.control.TextArea;
import javafx.scene.control.DatePicker;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class AjouterEvenementController {
    @FXML private TextField titreField;
    @FXML private TextArea descriptionField;
    @FXML private DatePicker dateDebutPicker;
    @FXML private DatePicker dateFinPicker;
    @FXML private TextField capaciteField;
    @FXML private TextField categorieIdField;
    @FXML private TextField lieuIdField;
    @FXML private TextField organisateurIdField;
    @FXML private TextField prixField;
    @FXML private TextField lieuProprietaireField;
    @FXML private TextField imageField;

    private EvenementService evenementService = new EvenementService();
    private static final String DEFAULT_STATUS = "en attente";
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @FXML
    private void handleAjouterEvenement() {
        try {
            int capacite = capaciteField.getText().isEmpty() ? 0 : Integer.parseInt(capaciteField.getText());
            int categorieId = categorieIdField.getText().isEmpty() ? 0 : Integer.parseInt(categorieIdField.getText());
            int lieuId = lieuIdField.getText().isEmpty() ? 0 : Integer.parseInt(lieuIdField.getText());
            int organisateurId = organisateurIdField.getText().isEmpty() ? 0 : Integer.parseInt(organisateurIdField.getText());
            double prix = prixField.getText().isEmpty() ? 0.0 : Double.parseDouble(prixField.getText());

            Evenement evenement = new Evenement(
                0, // ID will be generated by database
                titreField.getText(),
                descriptionField.getText(),
                dateDebutPicker.getValue().toString(),
                dateFinPicker.getValue().toString(),
                capacite,
                categorieId,
                lieuId,
                organisateurId,
                prix,
                DEFAULT_STATUS,
                lieuProprietaireField.getText(),
                imageField.getText()
            );

            evenementService.ajouter(evenement);
            clearFields();
            
        } catch (NumberFormatException e) {
            // Optionally show an alert here
            System.out.println("Erreur de format de nombre: " + e.getMessage());
        }
    }

    private void clearFields() {
        titreField.clear();
        descriptionField.clear();
        dateDebutPicker.setValue(null);
        dateFinPicker.setValue(null);
        capaciteField.clear();
        categorieIdField.clear();
        lieuIdField.clear();
        organisateurIdField.clear();
        prixField.clear();
        lieuProprietaireField.clear();
        imageField.clear();
    }
} 